- name: install influxdb # influx db is database which can keep track of the logs
  apt:
    package: ['influxdb','influxdb-client', 'python-pip']

- name: install requests module # needed for db creation
  pip:
    name: ['requests', 'influxdb']

    
