{
 "title": "Dash Bored",
 "time": { "from": "2019-12-11T18:38:19.562Z", "to": "2019-12-11T22:32:38.006Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Available Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda2\",instance=\"server1.island.awsome:9100\"}"
    }
   ]
  },
  {
   "title": "Node_CPU_Idle_Seconds_Total_Server1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu_seconds_total{instance=\"server1.island.awsome:9100\",mode=\"idle\"}"
    }
   ]
  },
  {
   "title": "Syslog_Messages_Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bind_IncomingTypeAQueries_Server2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_incoming_queries_total{instance=\"server2.island.awsome:9119\",job=\"bind\",type=\"A\"}"
    }
   ]
  },
  {
   "title": "MySQL_State",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Bind_IncomingTypeAQueries_Server1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_incoming_queries_total{instance=\"server1.island.awsome:9119\",type=\"A\"}"
    }
   ]
  },
  {
   "title": "Bind_State_Server1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bind_up{instance=\"server1.island.awsome:9119\"}"
    }
   ]
  },
  {
   "title": "Bind_State_Server2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bind_up{instance=\"server2.island.awsome:9119\"}"
    }
   ]
  },
  {
   "title": "Mysql_Requests_Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job='mysql'}"
    }
   ]
  },
  {
   "title": "Node_CPU_Idle_Seconds_Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu_seconds_total{instance=\"server2.island.awsome:9100\",mode=\"idle\"}"
    }
   ]
  }
 ]
}