---
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
locals:
  - 192.168.56.0/24
  - 127.0.0.0/24
  - 172.17.0.0/16
records:
  - type: NS
    entries:
      - name: island.awsome.
        address: server1.island.awsome.

      - name: island.awsome.
        address: server2.island.awsome.

  - type: A
    entries:
      - name: server1.island.awsome.
        address: 192.168.56.105

      - name: server2.island.awsome.
        address: 192.168.56.106

      - name: server.island.awsome.
        addresses:
          - 192.168.56.105
          - 192.168.56.106

  - type: CNAME
    entries:
      - name: prometheus.island.awsome.
        address: server2.island.awsome.

      - name: grafana.island.awsome.
        address: server1.island.awsome.

      - name: wordpress.island.awsome.
        address: server1.island.awsome.

