- name: Create wordpress container
  docker_container:
    name: "{{ container_name }}"
    image: wordpress
    state: started
    network_mode: bridge
    ports: "{{ host_port }}:80"
    detach: true
    env:
      WORDPRESS_DB_HOST: 192.168.56.106:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ secret }}"
      WORDPRESS_DB_NAME: wordpress
