---
- name: lab4 p1
  hosts: server1
  become: yes
  tasks:
  - name: Install apache2
    package:
      name: apache2
      state: present

  - name: Apache config 1 # Here we tell apache to use port 80 for wordpress and to use the index.php file from wordpress folder
    template:
      src: ./files/wordpress.conf
      dest: /etc/apache2/sites-enabled/wordpress.conf

  - name: Apache config 2 # Change the 000 defaults port 
    template:
      src: ./files/000-default.conf
      dest: /etc/apache2/sites-enabled/000-default.conf

  - name: Install PHP
    package:
      name: php
      state: present

  - name: Install wordpress
    package:
      name: wordpress
      state: present

  - name: wordpress config # Here we put the database connection config for wordpress
    template:
      src: ./files/config-localhost.php
      dest: /etc/wordpress/config-localhost.php

  - name: reload apache
    service:
      name: apache2
      state: reloaded



- name: lab4 p2
  hosts: server2
  become: yes
  tasks:
  - name: Install MySQL
    package:
      name: mysql-server
      state: present

  - name: Mysql conf #  by default listens to localhost, so 127.0.0.1 changed to 0.0.0.0
    template:
      src: ./files/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: Add DB file
    template:
      src: ./files/database.sql
      dest: /tmp/database.sql

  - name: Create DB & User # This runs the script and creates the database
    shell: mysql --defaults-file=/etc/mysql/debian.cnf < /tmp/database.sql

  - name: reload mysql
    service:
      name: mysql
      state: reloaded

  - name: Remove file
    file:
      path: /tmp/database.sql
      state: absent
