- name: Install MySQL
  package:
    name: mysql-server 
    state: present

- name: Mysql conf
  template:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Add DB file
  template:
    src: database.sql
    dest: /tmp/database.sql

- name: Create mysql user
  shell: mysql --defaults-file=/etc/mysql/debian.cnf < /tmp/database.sql

- name: reload mysql
  service:
    name: mysql
    state: restarted

- name: Remove file
  file:
    path: /tmp/database.sql
    state: absent
