- name: download go
  get_url:
    url: https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go1.13.3.linux-amd64.tar.gz

- name: unarchive
  unarchive:
    src: /opt/go1.13.3.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes

- name: add user
  user:
    name: "{{ bind_exporter_user }}"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37333932616330383065626233303035323964323337313865343166346266623935346432333039
          3339346561336433633031666366316639353734353263310a386466373033363366343137663031
          63373163623636316139383734393335613261653463663464636437613664636331383034653032
          3532323332343063300a303064363465303336353465646431336532663635616134343932626137
          3536
    state: present
    shell: /bin/bash

- name: Create a symbolic link # This is so we can run go command, it need to be in bin so we create a shortcut
  file:
    src: /opt/go/bin/go
    dest: /usr/local/bin/go
    state: link

- name: install gcc and essentials
  apt:
    package: build-essential

- name: go get # download bind_exporter
  shell: "go get github.com/digitalocean/bind_exporter"

- name: move go file in root
  command: cp -r /root/go /home/{{ bind_exporter_user }}/go

- name: bind config allow port
  template:
    src: named.conf
    dest: /etc/bind/named.conf
  notify: restart bind

- name: systemd bind_exporter
  template:
    src: bind_exporter.service
    dest: /etc/systemd/system/bind_exporter.service
  notify: restart systemd

- name: start bind_exporter service
  service:
    name: bind_exporter
    state: started
    enabled: yes
