- name: Install MySQL
  package:
    name: mysql-server 
    state: present

- name: install packages
  package:
    name: ['mysql-server', 'python-pip', 'python-mysqldb']
    state: present

- name: install docker component
  pip:
    name: PyMySQL

- name: create databases
  mysql_db:
    name: '{{ wordpress_db }}'
    state: present
    config_file: /etc/mysql/debian.cnf

- name: create database users
  mysql_user:
    name: '{{ wordpress_user }}'
    password: '{{ wordpress_password }}'
    priv: '{{ wordpress_db }}.*:ALL'
    host: "%"
    state: present
    config_file: /etc/mysql/debian.cnf
