---
- name: backup server
  hosts: server2
  become: yes
  tasks:
    - name: add user
      user:
        name: "{{ user }}"
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37333932616330383065626233303035323964323337313865343166346266623935346432333039
          3339346561336433633031666366316639353734353263310a386466373033363366343137663031
          63373163623636316139383734393335613261653463663464636437613664636331383034653032
          3532323332343063300a303064363465303336353465646431336532663635616134343932626137
          3536
        state: present
        groups: bind
        append: yes
        shell: /bin/bash

    - name: Create .ssh directory
      file:
        path: /home/{{ user }}/.ssh
        state: directory
        owner: "{{ user }}"

    - name: Create known_hosts file
      file:
        path: /home/{{ user }}/.ssh/known_hosts
        state: touch
        owner: "{{ user }}"

    - name: copy id_rsa3
      template:
        src: ./files/id_rsa3
        dest: /home/{{ user }}/.ssh/id_rsa

    - name: copy id_rsa3.pub
      template:
        src: ./files/id_rsa3.pub
        dest: /home/{{ user }}/.ssh/id_rsa.pub

    - name: place local ssh key
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', './files/id_rsa3.pub') }}"

    - name: place ssh key
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', './files/id_rsa2.pub') }}"

    - name: add ssh fingerprint # remote host's pub key hash for no prompt when connecting for the first time
      shell: ssh-keyscan -H localhost >> /home/{{ user }}/.ssh/known_hosts

    - name: Create /srv/backup
      file:
        path: /srv/backup
        state: directory
        owner: "{{ user }}"

    - name: Create /srv/backup/mysql_db.b
      file:
        path: /srv/backup/mysql_db.b
        state: directory
        owner: "{{ user }}"

    - name: Create /srv/backup/DNS_master.b
      file:
        path: /srv/backup/DNS_master.b
        state: directory
        owner: "{{ user }}"

    - name: Create /srv/backup/DNS_slave.b
      file:
        path: /srv/backup/DNS_slave.b
        state: directory
        owner: "{{ user }}"

    - name: install duplicity
      package:
        name: duplicity
        state: present
