- name: download mysqld_exporter
  get_url:
    url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz
    dest: /opt/mysqld_exporter-0.12.1.linux-amd64.tar.gz

- name: unarchive
  unarchive:
    remote_src: yes
    src: /opt/mysqld_exporter-0.12.1.linux-amd64.tar.gz
    dest: /opt/

- name: add user
  user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    state: present
    shell: /bin/bash

- name: create database users
  mysql_user:
    name: '{{ mysql_exporter_user }}'
    password: '{{ mysql_exporter_password }}'
    priv: '*.*:ALL'
    host: "localhost"
    state: present
    config_file: /etc/mysql/debian.cnf

- name: systemd mysqld_exporter
  template:
    src: mysqld_exporter.service
    dest: /etc/systemd/system/mysqld_exporter.service

- name: start mysqld_exporter service
  service:
    name: mysqld_exporter
    state: started
    enabled: yes
