---
- name: node_exporter
  hosts: servers
  become: yes
  vars:
    node_exporter_user: node_exporter
    bind_exporter_user: bind_exporter
  roles: # we seperated different playbooks dealing with different installations for better management and troubleshooting. They go in the roles dir by default
    - node_exporter

- name: prometheus
  hosts: server2
  become: yes
  vars:
     version: 2.14.0
     prometheus_user: root
     mysql_exporter_user: mysql_exporter
     mycnf_dest: /home/mysql_exporter/
     apache_exporter_user: apache_exporter
  roles:
    - prometheus
    - grafana
    - mysql_exporter
    - apache_exporter

- name: bind_exporter
  hosts: servers
  become: yes
  vars:
    node_exporter_user: node_exporter
    bind_exporter_user: bind_exporter
  roles:
    - bind_exporter
